repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff - Linting
        entry: pipenv run ruff check --fix
        language: system
        types: [python]
        stages: [pre-commit]

      - id: ruff-format
        name: Ruff - Format
        entry: pipenv run ruff format
        language: system
        types: [python]
        stages: [pre-commit]

      - id: mypy
        name: Type checking with mypy
        entry: pipenv run mypy src
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit]

      - id: pytest
        name: Run pytest suite
        entry: pipenv run pytest -v --cov=src
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-json
      - id: check-toml
